# Generated by Django 5.0.1 on 2024-01-15 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.CharField(choices=[('Dwarf', 'DWARF'), ('Elf', 'ELF'), ('Halfling', 'HALFLING'), ('Human', 'HUMAN'), ('Dragonborn', 'DRAGONBORN'), ('Gnome', 'GNOME'), ('Half-Elf', 'HALF_ELF'), ('Half-Orc', 'HALF_ORC'), ('Tiefling', 'TIEFLING')], default='Human', max_length=50)),
                ('character_class', models.CharField(choices=[('Barbarian', 'BARBARIAN'), ('Bard', 'BARD'), ('Cleric', 'CLERIC'), ('Druid', 'DRUID'), ('Fighter', 'FIGHTER'), ('Monk', 'MONK'), ('Paladin', 'PALADIN'), ('Ranger', 'RANGER'), ('Sorcerer', 'SORCERER'), ('Warlock', 'WARLOCK'), ('Wizard', 'WIZARD')], default='Barbarian', max_length=50)),
                ('strength', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('constitution', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('intelligence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('wisdom', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('charisma', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('alignment', models.CharField(choices=[('True Neutral', 'TRUE_NEUTRAL'), ('Lawful Neutral', 'LAWFUL_NEUTRAL'), ('Chaotic Neutral', 'CHAOTIC_NEUTRAL'), ('Neutral Good', 'NEUTRAL_GOOD'), ('Lawful Good', 'LAWFUL_GOOD'), ('Chaotic Good', 'CHAOTIC_GOOD'), ('Neutral Evil', 'NEUTRAL_EVIL'), ('Lawful Evil', 'LAWFUL_EVIL'), ('Chaotic Evil', 'CHAOTIC_EVIL')], default='True Neutral', max_length=50)),
                ('inventory', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
